export function buildSeedData() {
  const now = Date.now();
  const DAY = 24 * 60 * 60 * 1000;
  const iso = (d) => new Date(now + d * DAY).toISOString().slice(0, 10);

  return {
    profile: { name: 'Amelia Cross', tier: 'Explorer', memberSince: 2022, rating: 4.9 },
    settings: { darkMode: false, locationSharing: true, pushNotifications: true },
    favorites: ['swiss-alps', 'bali'],
    destinations: [
      {
        id: 'swiss-alps', name: 'Swiss Alps', country: 'Switzerland', price: 1120, rating: 4.9, reviewCount: 2341, tag: 'mountain',
        img: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=900&auto=format&fit=crop',
        safetyScore: 92, safetyLabel: 'Low risk · stable region · good emergency coverage',
        desc: 'Snow-capped peaks, glacial lakes, and storybook villages. The Swiss Alps pair postcard scenery with some of the most reliable infrastructure in the world — well-marked trails, responsive mountain rescue, and excellent connectivity even at altitude.',
        thumbs: ['https://images.unsplash.com/photo-1531366936337-7c912a4589a7?q=80&w=400&auto=format&fit=crop','https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?q=80&w=400&auto=format&fit=crop','https://images.unsplash.com/photo-1542224566954-d385d8a2c3b9?q=80&w=400&auto=format&fit=crop'],
        reviews: [{ name: 'Marco T.', avatar: 47, stars: 5, text: 'Felt completely at ease the whole trip — rescue posts everywhere and signal even on the trails.' },{ name: 'Hana K.', avatar: 21, stars: 4, text: 'Stunning views. Bring proper boots — some trails are steeper than they look on the map.' }],
        safetyPoints: [{ level: 'green', text: 'Low crime rate, stable political climate' },{ level: 'green', text: 'Mountain rescue average response: 14 min' },{ level: 'amber', text: 'Cellular coverage drops above 2,800m' },{ level: 'green', text: 'English widely spoken at medical facilities' }],
      },
      {
        id: 'bali', name: 'Bali', country: 'Indonesia', price: 780, rating: 4.8, reviewCount: 5012, tag: 'beach',
        img: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?q=80&w=900&auto=format&fit=crop',
        safetyScore: 78, safetyLabel: 'Moderate risk · watch road conditions',
        desc: 'Lush rice terraces, ocean temples, and a laid-back pace that makes it easy to stay a week longer than planned. Most safety concerns here center on traffic and water safety rather than crime.',
        thumbs: ['https://images.unsplash.com/photo-1518638150340-f706e86654de?q=80&w=400&auto=format&fit=crop','https://images.unsplash.com/photo-1604999333679-b86d54738315?q=80&w=400&auto=format&fit=crop'],
        reviews: [{ name: 'Priya S.', avatar: 32, stars: 5, text: 'Rented a scooter and regretted it within a day — traffic is genuinely chaotic. Everything else was wonderful.' },{ name: 'Ben O.', avatar: 14, stars: 4, text: 'Stomach issues are common, stick to bottled water and you will mostly be fine.' }],
        safetyPoints: [{ level: 'amber', text: 'Scooter accidents are the leading cause of tourist injury' },{ level: 'green', text: 'Low violent crime rate' },{ level: 'amber', text: 'Tap water is not safe to drink' },{ level: 'green', text: 'English widely spoken in tourist areas' }],
      },
      {
        id: 'santorini', name: 'Santorini', country: 'Greece', price: 890, rating: 4.9, reviewCount: 3120, tag: 'beach',
        img: 'https://images.unsplash.com/photo-1539020140153-e479b8c22e70?q=80&w=900&auto=format&fit=crop',
        safetyScore: 90, safetyLabel: 'Low risk · very tourist-friendly',
        desc: 'Whitewashed cliffside towns over a sapphire caldera. One of the most visited islands in the Aegean, with tourism infrastructure — clinics, transport, English signage — to match.',
        thumbs: ['https://images.unsplash.com/photo-1469796466635-455ede028aca?q=80&w=400&auto=format&fit=crop','https://images.unsplash.com/photo-1533105079780-92b9be482077?q=80&w=400&auto=format&fit=crop'],
        reviews: [{ name: 'Claire D.', avatar: 5, stars: 5, text: 'Felt safe walking back to our hotel late at night through Oia. Very calm island.' }],
        safetyPoints: [{ level: 'green', text: 'Very low crime rate' },{ level: 'amber', text: 'Steep cliffside paths — watch footing at night' },{ level: 'green', text: 'Excellent medical access for the size of the island' }],
      },
      {
        id: 'reykjavik', name: 'Reykjavík', country: 'Iceland', price: 640, rating: 4.8, reviewCount: 1890, tag: 'city',
        img: 'https://images.unsplash.com/photo-1504829857797-ddff29c27927?q=80&w=900&auto=format&fit=crop',
        safetyScore: 97, safetyLabel: 'Very low risk · one of the world\u2019s safest countries',
        desc: 'A small, walkable capital that doubles as the gateway to glaciers, geysers, and the northern lights. Iceland regularly tops global peace indices.',
        thumbs: ['https://images.unsplash.com/photo-1504541989-eecca36ef8d3?q=80&w=400&auto=format&fit=crop','https://images.unsplash.com/photo-1483347756197-71ef80e95f73?q=80&w=400&auto=format&fit=crop'],
        reviews: [{ name: 'Tom R.', avatar: 60, stars: 5, text: 'Drove the ring road solo as a woman and never once felt unsafe. Just watch the weather.' }],
        safetyPoints: [{ level: 'green', text: 'Ranked #1 on the Global Peace Index most years' },{ level: 'amber', text: 'Weather changes fast — check road conditions before driving' }],
      },
      {
        id: 'lisbon', name: 'Lisbon', country: 'Portugal', price: 510, rating: 4.7, reviewCount: 2200, tag: 'city',
        img: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?q=80&w=900&auto=format&fit=crop',
        safetyScore: 85, safetyLabel: 'Low risk · watch for pickpockets on trams',
        desc: 'Pastel facades, tiled stairways, and some of the best seafood in Europe at a fraction of Western European prices.',
        thumbs: ['https://images.unsplash.com/photo-1525625293386-3f8f99389edd?q=80&w=400&auto=format&fit=crop'],
        reviews: [{ name: 'Noah F.', avatar: 18, stars: 4, text: 'Tram 28 is a known pickpocket spot, keep bags zipped and to the front.' }],
        safetyPoints: [{ level: 'amber', text: 'Pickpocketing reported on Tram 28 and in busy squares' },{ level: 'green', text: 'Low violent crime' }],
      },
      {
        id: 'kyoto', name: 'Kyoto', country: 'Japan', price: 610, rating: 4.9, reviewCount: 4410, tag: 'culture',
        img: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?q=80&w=900&auto=format&fit=crop',
        safetyScore: 96, safetyLabel: 'Very low risk · excellent infrastructure',
        desc: 'Centuries-old temples and quiet bamboo groves a short walk from some of the most efficient transit on earth.',
        thumbs: ['https://images.unsplash.com/photo-1545569341-9eb8b30979d9?q=80&w=400&auto=format&fit=crop','https://images.unsplash.com/photo-1480796927426-f609979314bd?q=80&w=400&auto=format&fit=crop'],
        reviews: [{ name: 'Yuki M.', avatar: 11, stars: 5, text: 'Lost my wallet on a train platform and someone turned it in within the hour.' }],
        safetyPoints: [{ level: 'green', text: 'Among the lowest crime rates of any major city' },{ level: 'green', text: 'Trains run on time to the minute' }],
      },
      {
        id: 'tulum', name: 'Tulum', country: 'Mexico', price: 350, rating: 4.4, reviewCount: 1675, tag: 'budget',
        img: 'https://images.unsplash.com/photo-1518638150340-f706e86654de?q=80&w=900&auto=format&fit=crop',
        safetyScore: 64, safetyLabel: 'Exercise increased caution',
        desc: 'Jungle cenotes and beach clubs built into Mayan ruins. Tourist zones are well patrolled; exercise normal urban caution after dark.',
        thumbs: ['https://images.unsplash.com/photo-1518684079-3c830dcef090?q=80&w=400&auto=format&fit=crop'],
        reviews: [{ name: 'Greta L.', avatar: 8, stars: 4, text: 'Stick to the hotel zone at night and you will be fine. Daytime felt totally relaxed.' }],
        safetyPoints: [{ level: 'amber', text: 'Avoid walking alone outside tourist areas after dark' },{ level: 'green', text: 'Beach and hotel zones are well patrolled' }],
      },
      {
        id: 'banff', name: 'Banff', country: 'Canada', price: 720, rating: 4.8, reviewCount: 980, tag: 'mountain',
        img: 'https://images.unsplash.com/photo-1561134643-668f9057cc2c?q=80&w=900&auto=format&fit=crop',
        safetyScore: 94, safetyLabel: 'Very low risk · main hazard is wildlife, not crime',
        desc: 'Turquoise glacial lakes ringed by the Canadian Rockies. The biggest safety consideration here is wildlife awareness, not crime.',
        thumbs: ['https://images.unsplash.com/photo-1561134643-668f9057cc2c?q=80&w=400&auto=format&fit=crop'],
        reviews: [{ name: 'Liam P.', avatar: 19, stars: 5, text: 'Saw a bear from a very safe distance thanks to clear trail signage and warnings.' }],
        safetyPoints: [{ level: 'amber', text: 'Carry bear spray on backcountry trails' },{ level: 'green', text: 'Extremely low crime rate' }],
      },
      {
        id: 'marrakech', name: 'Marrakech', country: 'Morocco', price: 430, rating: 4.6, reviewCount: 1540, tag: 'culture',
        img: 'https://images.unsplash.com/photo-1597212720158-2e1ab78cf6fe?q=80&w=900&auto=format&fit=crop',
        safetyScore: 72, safetyLabel: 'Moderate risk · busy medina, watch belongings',
        desc: 'A maze of souks, riads, and spice markets in the shadow of the Atlas Mountains.',
        thumbs: ['https://images.unsplash.com/photo-1539020140153-e479b8c22e70?q=80&w=400&auto=format&fit=crop'],
        reviews: [{ name: 'Sara N.', avatar: 25, stars: 4, text: 'The medina is overwhelming at first but never felt unsafe, just busy. Negotiate prices up front.' }],
        safetyPoints: [{ level: 'amber', text: 'Petty theft reported in crowded souks' },{ level: 'green', text: 'Low rate of violent crime against tourists' }],
      },
      {
        id: 'queenstown', name: 'Queenstown', country: 'New Zealand', price: 980, rating: 4.9, reviewCount: 1290, tag: 'mountain',
        img: 'https://images.unsplash.com/photo-1589871173675-81fa11e3d56c?q=80&w=900&auto=format&fit=crop',
        safetyScore: 95, safetyLabel: 'Very low risk · adventure-sport injury is the main concern',
        desc: 'The self-styled adventure capital of the world — bungee jumping, jet boating, and some of the most dramatic scenery in the South Pacific.',
        thumbs: ['https://images.unsplash.com/photo-1469521669194-babb45599def?q=80&w=400&auto=format&fit=crop'],
        reviews: [{ name: 'Owen K.', avatar: 41, stars: 5, text: 'Every adventure operator we used had clear, serious safety briefings.' }],
        safetyPoints: [{ level: 'amber', text: 'Adventure sports carry inherent physical risk — choose licensed operators' },{ level: 'green', text: 'Very low crime' }],
      },
      {
        id: 'dolomites', name: 'Dolomites', country: 'Italy', price: 540, rating: 4.7, reviewCount: 860, tag: 'mountain',
        img: 'https://images.unsplash.com/photo-1551649001-7a2482d98d05?q=80&w=900&auto=format&fit=crop',
        safetyScore: 91, safetyLabel: 'Low risk · alpine hazards apply',
        desc: 'Jagged limestone peaks and rifugio hiking trails in northern Italy.',
        thumbs: ['https://images.unsplash.com/photo-1551649001-7a2482d98d05?q=80&w=400&auto=format&fit=crop'],
        reviews: [{ name: 'Elena V.', avatar: 3, stars: 5, text: 'Mountain huts (rifugi) were a great safety net — always someone nearby on the trail.' }],
        safetyPoints: [{ level: 'amber', text: 'Weather can shift quickly at altitude' },{ level: 'green', text: 'Well-maintained, well-marked trail network' }],
      },
      {
        id: 'algarve', name: 'Algarve', country: 'Portugal', price: 390, rating: 4.5, reviewCount: 1120, tag: 'budget',
        img: 'https://images.unsplash.com/photo-1583087913376-78cdb7e76d44?q=80&w=900&auto=format&fit=crop',
        safetyScore: 88, safetyLabel: 'Low risk · strong rip currents on the Atlantic side',
        desc: 'Golden cliffs, sea caves, and a noticeably lower cost of living than the rest of Western Europe.',
        thumbs: ['https://images.unsplash.com/photo-1583087913376-78cdb7e76d44?q=80&w=400&auto=format&fit=crop'],
        reviews: [{ name: 'Dana W.', avatar: 17, stars: 4, text: 'Watch flag warnings on the beaches — some have strong currents even on calm-looking days.' }],
        safetyPoints: [{ level: 'amber', text: 'Strong rip currents reported at several beaches — check flags' },{ level: 'green', text: 'Very low crime' }],
      },
    ],
    trips: [
      {
        id: 'trip-kyoto-1', destinationId: 'kyoto', place: 'Kyoto, Japan',
        img: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?q=80&w=900&auto=format&fit=crop',
        startDate: iso(12), endDate: iso(19), status: 'upcoming',
        steps: { flights: true, hotel: true, activities: false, packing: false },
        companionAvatars: [12, 33], companionsExtra: 2,
        days: {
          1: [
            { id: 't1', time: '08:30', icon: 'food', title: 'Breakfast at Café Bibliotic', note: 'Nakagyo Ward · 30 min walk from hotel' },
            { id: 't2', time: '10:00', icon: 'sight', title: 'Fushimi Inari Shrine', note: 'Allow 2.5 hrs · moderate hike' },
            { id: 't3', time: '14:00', icon: 'food', title: 'Lunch — Nishiki Market', note: 'Try the tako tamago' },
            { id: 't4', time: '19:00', icon: 'stay', title: 'Check in — Granbell Hotel', note: 'Confirmation #VY-8841' },
          ],
          2: [
            { id: 't5', time: '09:00', icon: 'sight', title: 'Arashiyama Bamboo Grove', note: 'Go early to beat crowds' },
            { id: 't6', time: '12:30', icon: 'food', title: 'Lunch near Tenryu-ji', note: '' },
          ],
          3: [], 4: [], 5: [],
        },
      },
      {
        id: 'trip-santorini-1', destinationId: 'santorini', place: 'Santorini, Greece',
        img: 'https://images.unsplash.com/photo-1539020140153-e479b8c22e70?q=80&w=900&auto=format&fit=crop',
        startDate: iso(41), endDate: iso(47), status: 'upcoming',
        steps: { flights: true, hotel: false, activities: false, packing: false },
        companionAvatars: [], companionsExtra: 0,
        days: { 1: [{ id: 's1', time: '17:00', icon: 'sight', title: 'Sunset at Oia Castle', note: 'Arrive 45 min early for a spot' }], 2: [], 3: [], 4: [], 5: [], 6: [] },
      },
      {
        id: 'trip-bali-1', destinationId: 'bali', place: 'Ubud, Bali',
        img: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?q=80&w=900&auto=format&fit=crop',
        startDate: iso(-110), endDate: iso(-102), status: 'past',
        steps: { flights: true, hotel: true, activities: true, packing: true },
        companionAvatars: [], companionsExtra: 0, days: { 1: [] }, reviewed: false,
      },
      {
        id: 'trip-lisbon-1', destinationId: 'lisbon', place: 'Lisbon, Portugal',
        img: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?q=80&w=900&auto=format&fit=crop',
        startDate: iso(-165), endDate: iso(-160), status: 'past',
        steps: { flights: true, hotel: true, activities: true, packing: true },
        companionAvatars: [], companionsExtra: 0, days: { 1: [] }, reviewed: true,
      },
    ],
    activeTripId: 'trip-kyoto-1',
    emergencyContacts: [
      { id: 'c1', name: 'James Cross', relation: 'Brother · primary', phone: '+1 555 014 2231', avatar: 5 },
      { id: 'c2', name: 'Sofia Marin', relation: 'Best friend', phone: '+1 555 098 7711', avatar: 9 },
    ],
    notifications: [
      { id: 'n1', type: 'trip', title: 'Kyoto trip is in 12 days', body: 'Finish booking activities — you\u2019re 64% done planning.', time: Date.now() - 2 * 60 * 60 * 1000, read: false },
      { id: 'n2', type: 'safety', title: 'Safety check-in complete', body: 'Your location was shared successfully with James Cross.', time: Date.now() - 26 * 60 * 60 * 1000, read: false },
      { id: 'n3', type: 'system', title: 'Welcome to Vouya', body: 'Add an emergency contact to get the most out of Safety features.', time: Date.now() - 4 * 24 * 60 * 60 * 1000, read: true },
    ],
    safetyActivity: [
      { id: 'a1', icon: '📍', text: 'Location check-in', time: Date.now() - 2 * 60 * 1000 },
      { id: 'a2', icon: '🔋', text: 'Battery dropped below 85%', time: Date.now() - 40 * 60 * 1000 },
    ],
    paymentMethods: [{ id: 'pm1', brand: 'Visa', last4: '4242' }],
    posts: [
      { id: 'post-1', type: 'review', destinationId: 'kyoto', authorIsMe: false, authorName: 'Yuki M.', authorAvatar: 11, stars: 5, text: 'Lost my wallet on a train platform and someone turned it in within the hour. Felt safer here than at home.', img: null, time: Date.now() - 3 * 24 * 60 * 60 * 1000, likes: 24, likedByMe: false },
      { id: 'post-2', type: 'moment', destinationId: 'santorini', authorIsMe: false, authorName: 'Claire D.', authorAvatar: 5, stars: null, text: 'Sunset in Oia hit different tonight. Walked back through town after dark and never once felt unsafe — well-lit streets the whole way.', img: 'https://images.unsplash.com/photo-1469796466635-455ede028aca?q=80&w=900&auto=format&fit=crop', time: Date.now() - 9 * 60 * 60 * 1000, likes: 41, likedByMe: true },
      { id: 'post-3', type: 'review', destinationId: 'bali', authorIsMe: false, authorName: 'Priya S.', authorAvatar: 32, stars: 4, text: 'Rented a scooter and regretted it within a day — traffic is genuinely chaotic. Everything else was wonderful, just budget for a driver instead.', img: null, time: Date.now() - 30 * 60 * 60 * 1000, likes: 17, likedByMe: false },
      { id: 'post-4', type: 'moment', destinationId: 'kyoto', authorIsMe: false, authorName: 'Marco T.', authorAvatar: 47, stars: null, text: 'Bamboo grove at sunrise, basically alone. Worth the early alarm.', img: 'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?q=80&w=900&auto=format&fit=crop', time: Date.now() - 50 * 60 * 60 * 1000, likes: 63, likedByMe: false },
    ],
  };
}
